"""WorldFoundry-owned primitives with no model identity.

Re-exports are loaded lazily via :func:`__getattr__` so importing
:mod:`worldfoundry.core` does not eagerly import every submodule.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

from worldfoundry.core import log_filters as _log_filters  # noqa: F401

_EXPORT_MODULES = {
    "assign_state_dict_strict": "worldfoundry.core.checkpoint",
    "euler_angles_to_rotation_matrix_zyx": "worldfoundry.core.geometry",
    "compose_horizontal_views": "worldfoundry.core.utils",
    "split_horizontal_views": "worldfoundry.core.utils",
    "AttentionBackendInfo": "worldfoundry.core.attention.native",
    "AttentionKernelCapability": "worldfoundry.core.attention",
    "AutoTorchModule": "worldfoundry.core.vram",
    "AutoWrappedLinear": "worldfoundry.core.vram",
    "AutoWrappedModule": "worldfoundry.core.vram",
    "AutoWrappedNonRecurseModule": "worldfoundry.core.vram",
    "CudaSyncTimer": "worldfoundry.core.time",
    "DiskMap": "worldfoundry.core.vram",
    "DTensorFastEmaModelUpdater": "worldfoundry.core.distributed",
    "FlowMatchScheduler": "worldfoundry.core.nn.diffusion_schedulers",
    "LayerwiseOffloadHandle": "worldfoundry.core.vram",
    "DuplicateRegistryKeyError": "worldfoundry.core.registry",
    "DropPath": "worldfoundry.core.nn.layers",
    "LayerScale": "worldfoundry.core.nn.layers",
    "Mlp": "worldfoundry.core.nn.layers",
    "ModelConfig": "worldfoundry.core.model_loading",
    "ModelMetaArgs": "worldfoundry.core.attention",
    "ModelLoaderRegistry": "worldfoundry.core.model_loading",
    "PackedCoreAttnParams": "worldfoundry.core.attention",
    "PackedCrossAttnParams": "worldfoundry.core.attention",
    "PatchGridSpec": "worldfoundry.core.nn.patching",
    "PatchEmbed": "worldfoundry.core.nn.layers",
    "PatchEmbed_Mlp": "worldfoundry.core.nn.layers",
    "Permute": "worldfoundry.core.nn.layers",
    "PixelUnshuffle": "worldfoundry.core.nn.layers",
    "PositionGetter": "worldfoundry.core.attention.rope_2d",
    "RegistryError": "worldfoundry.core.registry",
    "RegistryItem": "worldfoundry.core.registry",
    "SchedulerInterface": "worldfoundry.core.nn.diffusion_schedulers",
    "TransformerShapeSpec": "worldfoundry.core.nn.transformer",
    "TypedRegistry": "worldfoundry.core.registry",
    "UnknownRegistryKeyError": "worldfoundry.core.registry",
    "InferenceArtifactSpec": "worldfoundry.core.inference",
    "InferenceCheckpointRef": "worldfoundry.core.inference",
    "InferenceFieldSpec": "worldfoundry.core.inference",
    "InferenceParams": "worldfoundry.core.inference_state",
    "InferenceTaskProfile": "worldfoundry.core.inference",
    "InferenceVariantSpec": "worldfoundry.core.inference",
    "LINGBOT_VARIANT_BASE_ACT_PREVIEW": "worldfoundry.core.inference",
    "LINGBOT_VARIANT_BASE_CAM": "worldfoundry.core.inference",
    "LINGBOT_VARIANT_FAST": "worldfoundry.core.inference",
    "LINGBOT_WORLD_INFERENCE_SPEC": "worldfoundry.core.inference",
    "LINGBOT_WORLD_MODEL_ID": "worldfoundry.core.inference",
    "ModelInferenceSpec": "worldfoundry.core.inference",
    "WorldFoundryInferenceInfraState": "worldfoundry.core.inference",
    "SwiGLU": "worldfoundry.core.nn.layers",
    "SwiGLUFFN": "worldfoundry.core.nn.layers",
    "SwiGLUFFNFused": "worldfoundry.core.nn.layers",
    "TileProcessor": "worldfoundry.core.io",
    "UlyssesScheduler": "worldfoundry.core.attention",
    "RotaryPositionEmbedding2D": "worldfoundry.core.attention.rope_2d",
    "apply_nd_rotary_embedding": "worldfoundry.core.attention.rope_nd",
    "apply_rotary_embedding": "worldfoundry.core.attention.rope",
    "attention_backend_capability": "worldfoundry.core.attention",
    "attention_backend_from_env": "worldfoundry.core.attention",
    "attention_forward": "worldfoundry.core.attention.dispatch",
    "attention_backend_report": "worldfoundry.core.attention",
    "attention_backend_info": "worldfoundry.core.attention.native",
    "attention_backend_context": "worldfoundry.core.attention.native",
    "attention_head_dim": "worldfoundry.core.nn.transformer",
    "autocast_context": "worldfoundry.core.inference",
    "causal_attention_mask": "worldfoundry.core.nn.transformer",
    "broadcast_dtensor_model_states": "worldfoundry.core.distributed",
    "clip_grad_norm_": "worldfoundry.core.gradient",
    "clip_grads_with_norm_": "worldfoundry.core.gradient",
    "compile_module_if_enabled": "worldfoundry.core.inference",
    "clear_inference_runtime_cache": "worldfoundry.core.runtime_cache",
    "coerce_video_frames": "worldfoundry.core.io",
    "Color": "worldfoundry.core.io",
    "crop_and_resize": "worldfoundry.core.io",
    "CSOHelper": "worldfoundry.core.attention",
    "cp_post_process": "worldfoundry.core.attention",
    "cp_pre_process": "worldfoundry.core.attention",
    "copy_uri": "worldfoundry.core.io",
    "cso_communication": "worldfoundry.core.attention",
    "cuda_visible_devices_from_device": "worldfoundry.core.device",
    "destroy_model_parallel": "worldfoundry.core.distributed",
    "dist_init": "worldfoundry.core.distributed",
    "dump_serialized": "worldfoundry.core.io",
    "divide": "worldfoundry.core.utils",
    "drop_path": "worldfoundry.core.nn.layers",
    "enable_layerwise_cpu_offload": "worldfoundry.core.vram",
    "env_is_true": "worldfoundry.core.utils",
    "exists_uri": "worldfoundry.core.io",
    "extract_frames_from_video_url": "worldfoundry.core.io",
    "file_sha256": "worldfoundry.core.io",
    "get_1d_rotary_pos_embed": "worldfoundry.core.attention.rope_nd",
    "get_meshgrid_nd": "worldfoundry.core.attention.rope_nd",
    "get_nd_rotary_pos_embed": "worldfoundry.core.attention.rope_nd",
    "gpu_supports_flash_attention": "worldfoundry.core.attention",
    "flattened_multihead_attention": "worldfoundry.core.attention",
    "hash_model_file": "worldfoundry.core.model_loading",
    "hash_state_dict_keys": "worldfoundry.core.model_loading",
    "generic_model_inference_spec": "worldfoundry.core.inference",
    "get_video_details": "worldfoundry.core.io",
    "get_model_inference_spec": "worldfoundry.core.inference",
    "get_local_tensor_if_dtensor": "worldfoundry.core.distributed",
    "get_total_norm": "worldfoundry.core.gradient",
    "build_rename_dict": "worldfoundry.core.model_loading",
    "infer_serialization_format": "worldfoundry.core.io",
    "init_pp_scheduler": "worldfoundry.core.distributed",
    "init_weights_on_device": "worldfoundry.core.vram",
    "initialize_model_parallel": "worldfoundry.core.distributed",
    "inference_infra_state": "worldfoundry.core.inference",
    "install_worldfoundry_inference_infra": "worldfoundry.core.inference",
    "is_last_rank": "worldfoundry.core.distributed",
    "is_last_tp_cp_rank": "worldfoundry.core.distributed",
    "list_model_inference_specs": "worldfoundry.core.inference",
    "is_remote_uri": "worldfoundry.core.io",
    "join_uri": "worldfoundry.core.io",
    "layer_scale": "worldfoundry.core.nn.normalization",
    "layerwise_offload_mutation_scope": "worldfoundry.core.vram",
    "load_model": "worldfoundry.core.model_loading",
    "load_model_loader_registry": "worldfoundry.core.model_loading",
    "load_model_with_disk_offload": "worldfoundry.core.model_loading",
    "load_serialized": "worldfoundry.core.io",
    "load_frames_from_video": "worldfoundry.core.io",
    "load_safetensors_into_model_streaming": "worldfoundry.core.checkpoint",
    "load_sharded_safetensors_parallel_with_progress": "worldfoundry.core.checkpoint",
    "load_state_dict": "worldfoundry.core.model_loading",
    "load_state_dict_from_safetensors_index": "worldfoundry.core.model_loading",
    "load_torch_checkpoint": "worldfoundry.core.model_loading",
    "load_torch_state_dict": "worldfoundry.core.model_loading",
    "load_video_frames": "worldfoundry.core.io",
    "LowMemoryImageFolder": "worldfoundry.core.io",
    "LowMemoryVideo": "worldfoundry.core.io",
    "load_pil_image": "worldfoundry.core.utils",
    "materialize_video_input": "worldfoundry.core.io",
    "materialize_image_input": "worldfoundry.core.utils",
    "materialize_hf_snapshot": "worldfoundry.core.io.hf",
    "maybe_download_hf_repo_on_rank0": "worldfoundry.core.io",
    "merge_video_audio": "worldfoundry.core.io",
    "merge_attention_heads": "worldfoundry.core.nn.transformer",
    "mlp_hidden_size": "worldfoundry.core.nn.transformer",
    "named_apply": "worldfoundry.core.nn.module_utils",
    "model_inference_spec": "worldfoundry.core.inference",
    "model_parallel_is_initialized": "worldfoundry.core.distributed",
    "normalize_attention_backend": "worldfoundry.core.attention",
    "normalize_action_values": "worldfoundry.core.action_normalization",
    "piecewise_attention": "worldfoundry.core.attention",
    "piecewise_attention_available": "worldfoundry.core.attention",
    "normalize_registry_key": "worldfoundry.core.registry",
    "open_uri": "worldfoundry.core.io",
    "parse_uri_scheme": "worldfoundry.core.io",
    "package_module_root": "worldfoundry.core.io",
    "patchify_image": "worldfoundry.core.nn.patching",
    "probe_attention_backends": "worldfoundry.core.attention",
    "read_binary_uri": "worldfoundry.core.io",
    "read_image_as_video_tensor": "worldfoundry.core.io",
    "read_text_uri": "worldfoundry.core.io",
    "read_video": "worldfoundry.core.io",
    "resize_video_tensor_to_resolution": "worldfoundry.core.io",
    "HF_URI_SCHEME": "worldfoundry.core.io",
    "hf_download_or_fpath": "worldfoundry.core.io",
    "resolve_hf_path": "worldfoundry.core.io",
    "resolve_hf_snapshot_path": "worldfoundry.core.io",
    "resolve_local_checkpoint_file": "worldfoundry.core.io",
    "resolve_local_hf_model_path": "worldfoundry.core.io",
    "resolve_inference_device": "worldfoundry.core.device",
    "resolve_inference_dtype": "worldfoundry.core.device",
    "run_torchrun_module": "worldfoundry.core.process",
    "stack_or_pad_tensors": "worldfoundry.core.utils",
    "standardize_quaternion_xyzw": "worldfoundry.core.geometry",
    "torchrun_module_command": "worldfoundry.core.process",
    "resolve_attention_backend": "worldfoundry.core.attention",
    "resolve_transformers_attention_implementation": "worldfoundry.core.attention",
    "routed_swiglu_moe_pytorch": "worldfoundry.core.kernels",
    "routed_swiglu_moe": "worldfoundry.core.kernels",
    "routed_swiglu_moe_triton": "worldfoundry.core.kernels",
    "rms_norm": "worldfoundry.core.nn.normalization",
    "ray_condition": "worldfoundry.core.geometry",
    "quaternion_xyzw_to_rotation_matrix": "worldfoundry.core.geometry",
    "rotation_matrix_to_euler_angles_opencv": "worldfoundry.core.geometry",
    "rotation_matrix_to_euler_angles_zyx": "worldfoundry.core.geometry",
    "rotation_matrix_to_quaternion_wxyz": "worldfoundry.core.geometry",
    "rotation_matrix_to_quaternion_xyzw": "worldfoundry.core.geometry",
    "rotary_frequencies": "worldfoundry.core.attention.rope",
    "rotate_half": "worldfoundry.core.attention.rope",
    "scaled_dot_product_attention": "worldfoundry.core.attention.native",
    "save_frames": "worldfoundry.core.io",
    "save_image_or_video_tensor": "worldfoundry.core.io",
    "save_video": "worldfoundry.core.io",
    "save_video_frames": "worldfoundry.core.io",
    "save_video_with_audio": "worldfoundry.core.io",
    "search_for_images": "worldfoundry.core.io",
    "search_for_embeddings": "worldfoundry.core.model_loading",
    "search_for_files": "worldfoundry.core.model_loading",
    "search_parameter": "worldfoundry.core.model_loading",
    "select_modality_statistics": "worldfoundry.core.action_normalization",
    "as_list": "worldfoundry.core.utils",
    "jsonable": "worldfoundry.core.io",
    "mean_flat": "worldfoundry.core.utils",
    "ParallelHelper": "worldfoundry.core.io",
    "PPScheduler": "worldfoundry.core.distributed",
    "pp_scheduler": "worldfoundry.core.distributed",
    "print_per_rank": "worldfoundry.core.distributed",
    "print_rank_0": "worldfoundry.core.distributed",
    "set_random_seed": "worldfoundry.core.utils",
    "skip_model_initialization": "worldfoundry.core.vram",
    "split_state_dict_with_prefix": "worldfoundry.core.model_loading",
    "varlen_scaled_dot_product_attention": "worldfoundry.core.attention.varlen",
    "validate_state_dict_compatibility": "worldfoundry.core.checkpoint",
    "split_attention_heads": "worldfoundry.core.nn.transformer",
    "transformer_shape_spec": "worldfoundry.core.nn.transformer",
    "unpatchify_image": "worldfoundry.core.nn.patching",
    "unnormalize_action_values": "worldfoundry.core.action_normalization",
    "utc_now_iso": "worldfoundry.core.time",
    "worldfoundry_inference_context": "worldfoundry.core.inference",
    "wrap_runner_for_worldfoundry_core": "worldfoundry.core.inference",
    "video_tensor_to_uint8_frames": "worldfoundry.core.io",
    "VideoData": "worldfoundry.core.io",
    "write_binary_uri": "worldfoundry.core.io",
    "write_text_uri": "worldfoundry.core.io",
    "write_video": "worldfoundry.core.io",
    "write_video_torchvision": "worldfoundry.core.io",
    "zero_module": "worldfoundry.core.nn.layers",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})


__all__ = sorted(_EXPORT_MODULES)
