"""
A specialized memory module for storing and retrieving visual artifacts (images and videos)
generated by a model.

This module provides the `VideoArtifactMemory` class, which extends `BaseMemory`
to handle the specific characteristics of visual media. It includes functionality
to infer content types, extract keyframes from videos, and prioritize image retrieval.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

from worldfoundry.core.memory import BaseMemory
from worldfoundry.core.memory.media import extract_last_frame, infer_content_type


class VideoArtifactMemory(BaseMemory):
    """
    Rolling memory for one visual-generation model's image/video artifacts.

    This class extends `BaseMemory` to provide specific functionality for handling
    visual media, such as images and videos generated by an AI model. It allows
    recording artifacts with associated metadata and selecting them based on type
    preference, including special handling for video frames.
    """

    MODEL_ID: str | None = None

    def __init__(self, capacity: Optional[int] = None, model_id: str | None = None, **kwargs: Any):
        """
        Initializes the VideoArtifactMemory instance.

        Args:
            capacity (Optional[int]): The maximum number of records to store.
                                      If None, the memory capacity is unbounded.
            model_id (Optional[str]): An identifier for the model generating the artifacts.
                                      If provided, it will override the class-level MODEL_ID.
            **kwargs (Any): Additional keyword arguments passed to the BaseMemory constructor.
        """
        super().__init__(capacity=capacity, **kwargs)
        # Set the model_id for this instance, preferring the constructor argument over the class attribute.
        self.model_id = model_id or self.MODEL_ID

    def record(self, data: Any, metadata: Optional[Dict[str, Any]] = None, **kwargs: Any):
        """
        Records a new visual artifact (image or video) into memory.

        This method processes the input data, infers its content type, and extracts
        additional relevant information (e.g., the last frame for videos) before
        storing it. It also attaches the `model_id` if available.

        Args:
            data (Any): The artifact content to record (e.g., an image byte string, a video object).
            metadata (Optional[Dict[str, Any]]): A dictionary of additional metadata for the record.
            **kwargs (Any): Arbitrary keyword arguments that will be added to the record's metadata.
        """
        # Combine provided metadata from `kwargs` and the `metadata` dictionary.
        entry_metadata = {**kwargs, **dict(metadata or {})}
        if self.model_id is not None:
            # Attach the model_id to the metadata if it's set.
            entry_metadata = {"model_id": self.model_id, **entry_metadata}

        content_type = infer_content_type(data)
        if content_type == "video":
            # For video content, attempt to extract the last frame and store it in metadata.
            # This allows treating videos as if they have an 'image' representation for selection.
            last_frame = extract_last_frame(data)
            if last_frame is not None:
                entry_metadata["last_frame"] = last_frame

        self.append_record(
            data,
            # Determine the 'kind' of record, preferring a 'type' specified in metadata
            # over the inferred content_type.
            kind=str(entry_metadata.get("type") or content_type),
            metadata=entry_metadata,
        )

    def select(self, context_query: Optional[Any] = None, prefer_type: str = "image", **kwargs: Any):
        """
        Selects and returns a relevant visual artifact from memory based on preference.

        This method iterates through the stored artifacts in reverse chronological order
        (most recent first) and tries to find an item matching the `prefer_type`.
        It has special logic to prioritize actual images or video last frames if "image"
        is the preferred type.

        Args:
            context_query (Optional[Any]): This parameter is not used in this implementation.
            prefer_type (str): The desired type of artifact to retrieve (e.g., "image", "video").
            **kwargs (Any): This parameter is not used in this implementation.

        Returns:
            Any: The content of the selected artifact, or None if no matching artifact is found.
        """
        del context_query, kwargs  # Unused parameters are explicitly deleted.
        for item in reversed(self.storage):
            # If "image" is preferred, prioritize actual image artifacts or the last frame of a video.
            if prefer_type == "image":
                if item["type"] == "image":
                    return item["content"]
                if item["metadata"].get("last_frame") is not None:
                    return item["metadata"]["last_frame"]
            # If the item's type matches the preferred type, return its content.
            if item["type"] == prefer_type:
                return item["content"]
        # If no matching artifact is found after iterating all stored items, return None.
        return None

    def manage(self, action: str = "reset", **kwargs: Any):
        """
        Performs management actions on the memory, such as resetting or evicting.

        Args:
            action (str): The specific action to perform. Supported actions include:
                          - "reset": Clears all stored records.
                          - "evict": Evicts the oldest record if the memory has a capacity.
            **kwargs (Any): This parameter is not used in this implementation.
        """
        del kwargs  # Unused parameter is explicitly deleted.
        if action == "reset":
            self.reset_records()
            return
        if action == "evict" and self.capacity is not None:
            # Evict an item only if the memory has a defined capacity.
            self._store.evict()


__all__ = ["VideoArtifactMemory"]