"""Module for base_models -> diffusion_model -> diffsynth -> configs -> vram_management_module_maps.py functionality."""

flux_general_vram_config = {
    "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
    "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
    "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
    "torch.nn.GroupNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    "diffsynth.models.general_modules.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    "diffsynth.models.flux_lora_encoder.LoRALayerBlock": "worldfoundry.core.vram.layers.AutoWrappedModule",
    "diffsynth.models.flux_lora_patcher.LoraMerger": "worldfoundry.core.vram.layers.AutoWrappedModule",
}

VRAM_MANAGEMENT_MODULE_MAPS = {
    "diffsynth.models.qwen_image_dit.QwenImageDiT": {
        "diffsynth.models.qwen_image_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.qwen_image_text_encoder.QwenImageTextEncoder": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VLRotaryEmbedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VisionPatchEmbed": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.qwen2_5_vl.modeling_qwen2_5_vl.Qwen2_5_VisionRotaryEmbedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.qwen_image_vae.QwenImageVAE": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.qwen_image_vae.QwenImageRMS_norm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.qwen_image_controlnet.BlockWiseControlBlock": {
        "diffsynth.models.qwen_image_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
    },
    "diffsynth.models.siglip2_image_encoder.Siglip2ImageEncoder": {
        "transformers.models.siglip.modeling_siglip.SiglipVisionEmbeddings": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip.modeling_siglip.SiglipMultiheadAttentionPoolingHead": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
    },
    "diffsynth.models.dinov3_image_encoder.DINOv3ImageEncoder": {
        "transformers.models.dinov3_vit.modeling_dinov3_vit.DINOv3ViTLayerScale": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.dinov3_vit.modeling_dinov3_vit.DINOv3ViTRopePositionEmbedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.dinov3_vit.modeling_dinov3_vit.DINOv3ViTEmbeddings": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
    },
    "diffsynth.models.qwen_image_image2lora.QwenImageImage2LoRAModel": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
    },
    "diffsynth.models.wan_video_animate_adapter.WanAnimateAdapter": {
        "diffsynth.models.wan_video_animate_adapter.FaceEncoder": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_animate_adapter.EqualLinear": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_animate_adapter.ConvLayer": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_animate_adapter.FusedLeakyReLU": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_animate_adapter.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv1d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_dit_s2v.WanS2VModel": {
        "diffsynth.models.wan_video_dit.Head": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_dit_s2v.WanS2VDiTBlock": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_dit_s2v.CausalAudioEncoder": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_dit.WanModel": {
        "diffsynth.models.wan_video_dit.MLP": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_dit.DiTBlock": "worldfoundry.core.vram.layers.AutoWrappedNonRecurseModule",
        "diffsynth.models.wan_video_dit.Head": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_image_encoder.WanImageEncoder": {
        "diffsynth.models.wan_video_image_encoder.VisionTransformer": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_mot.MotWanModel": {
        "diffsynth.models.wan_video_mot.MotWanAttentionBlock": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_motion_controller.WanMotionControllerModel": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
    },
    "diffsynth.models.wan_video_text_encoder.WanTextEncoder": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_text_encoder.T5RelativeEmbedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_text_encoder.T5LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_vace.VaceWanModel": {
        "diffsynth.models.wan_video_dit.DiTBlock": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_vae.WanVideoVAE": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_vae.RMS_norm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_vae.CausalConv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_vae.Upsample": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.SiLU": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Dropout": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wan_video_vae.WanVideoVAE38": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_vae.RMS_norm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_vae.CausalConv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.wan_video_vae.Upsample": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.SiLU": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Dropout": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.wav2vec.WanS2VAudioEncoder": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Conv1d": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.longcat_video_dit.LongCatVideoTransformer3DModel": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv3d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.longcat_video_dit.RMSNorm_FP32": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "diffsynth.models.longcat_video_dit.LayerNorm_FP32": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.flux_dit.FluxDiT": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "diffsynth.models.flux_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.flux_text_encoder_clip.FluxTextEncoderClip": flux_general_vram_config,
    "diffsynth.models.flux_vae.FluxVAEEncoder": flux_general_vram_config,
    "diffsynth.models.flux_vae.FluxVAEDecoder": flux_general_vram_config,
    "diffsynth.models.flux_controlnet.FluxControlNet": flux_general_vram_config,
    "diffsynth.models.flux_infiniteyou.InfiniteYouImageProjector": flux_general_vram_config,
    "diffsynth.models.flux_ipadapter.FluxIpAdapter": flux_general_vram_config,
    "diffsynth.models.flux_lora_patcher.FluxLoraPatcher": flux_general_vram_config,
    "diffsynth.models.step1x_connector.Qwen2Connector": flux_general_vram_config,
    "diffsynth.models.flux_lora_encoder.FluxLoRAEncoder": flux_general_vram_config,
    "diffsynth.models.flux_text_encoder_t5.FluxTextEncoderT5": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.t5.modeling_t5.T5LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.t5.modeling_t5.T5DenseActDense": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.t5.modeling_t5.T5DenseGatedActDense": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.flux_ipadapter.SiglipVisionModelSO400M": {
        "transformers.models.siglip.modeling_siglip.SiglipVisionEmbeddings": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip.modeling_siglip.SiglipEncoder": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.siglip.modeling_siglip.SiglipMultiheadAttentionPoolingHead": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.MultiheadAttention": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.flux2_dit.Flux2DiT": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.LayerNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.flux2_text_encoder.Flux2TextEncoder": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "transformers.models.mistral.modeling_mistral.MistralRMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.flux2_vae.Flux2VAE": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "torch.nn.Conv2d": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.GroupNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.z_image_text_encoder.ZImageTextEncoder": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "transformers.models.qwen3.modeling_qwen3.Qwen3RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
        "torch.nn.Embedding": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
    "diffsynth.models.z_image_dit.ZImageDiT": {
        "torch.nn.Linear": "worldfoundry.core.vram.layers.AutoWrappedLinear",
        "diffsynth.models.z_image_dit.RMSNorm": "worldfoundry.core.vram.layers.AutoWrappedModule",
    },
}
