"""Lazy miscellaneous utility exports."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_SUBMODULES = {
    "array_tensor_utils": "worldfoundry.core.utils.array_tensor_utils",
    "functional_utils": "worldfoundry.core.utils.functional_utils",
    "image_utils": "worldfoundry.core.utils.image_utils",
    "lazy_module": "worldfoundry.core.utils.lazy_module",
    "mask_data": "worldfoundry.core.utils.mask_data",
    "misc_utils": "worldfoundry.core.utils.misc_utils",
    "torch_utils": "worldfoundry.core.utils.torch_utils",
    "video_utils": "worldfoundry.core.utils.video_utils",
}

_EXPORT_MODULES = {
    "AverageMeter": "worldfoundry.core.utils.torch_utils",
    "ClassRegistry": "worldfoundry.core.utils.functional_utils",
    "Cv2Display": "worldfoundry.core.utils.image_utils",
    "DDPMethodWrapper": "worldfoundry.core.utils.torch_utils",

    "Every": "worldfoundry.core.utils.misc_utils",
    "LazyModule": "worldfoundry.core.utils.lazy_module",
    "NoopContext": "worldfoundry.core.utils.functional_utils",
    "NoopObject": "worldfoundry.core.utils.functional_utils",
    "Once": "worldfoundry.core.utils.misc_utils",
    "PeriodicEvent": "worldfoundry.core.utils.misc_utils",
    "RunningMeanStd": "worldfoundry.core.utils.torch_utils",
    "accepts_kwargs": "worldfoundry.core.utils.functional_utils",
    "accepts_varargs": "worldfoundry.core.utils.functional_utils",

    "add_batch_dim": "worldfoundry.core.utils.array_tensor_utils",
    "any_assign": "worldfoundry.core.utils.array_tensor_utils",
    "any_chunk": "worldfoundry.core.utils.array_tensor_utils",
    "any_concat": "worldfoundry.core.utils.array_tensor_utils",
    "any_describe": "worldfoundry.core.utils.array_tensor_utils",
    "any_describe_str": "worldfoundry.core.utils.array_tensor_utils",
    "any_fill_": "worldfoundry.core.utils.array_tensor_utils",
    "any_get_shape": "worldfoundry.core.utils.array_tensor_utils",
    "any_mean": "worldfoundry.core.utils.array_tensor_utils",
    "any_ones_like": "worldfoundry.core.utils.array_tensor_utils",
    "any_slice": "worldfoundry.core.utils.array_tensor_utils",
    "any_stack": "worldfoundry.core.utils.array_tensor_utils",
    "any_to_primitive": "worldfoundry.core.utils.array_tensor_utils",
    "any_transpose_first_two_axes": "worldfoundry.core.utils.array_tensor_utils",
    "any_variance": "worldfoundry.core.utils.array_tensor_utils",
    "any_zero_": "worldfoundry.core.utils.array_tensor_utils",
    "any_zeros_like": "worldfoundry.core.utils.array_tensor_utils",
    "argmax": "worldfoundry.core.utils.misc_utils",
    "assert_has_keys": "worldfoundry.core.utils.functional_utils",
    "assert_implements_method": "worldfoundry.core.utils.functional_utils",
    "as_list": "worldfoundry.core.utils.functional_utils",
    "basic_image_tensor_preprocess": "worldfoundry.core.utils.image_utils",
    "call_once": "worldfoundry.core.utils.functional_utils",
    "chunk_seq": "worldfoundry.core.utils.array_tensor_utils",
    "classify_accuracy": "worldfoundry.core.utils.torch_utils",
    "clip_grad_norm": "worldfoundry.core.utils.torch_utils",
    "clip_grad_value": "worldfoundry.core.utils.torch_utils",
    "clone_model": "worldfoundry.core.utils.torch_utils",
    "contains_rnn": "worldfoundry.core.utils.torch_utils",
    "count_parameters": "worldfoundry.core.utils.torch_utils",
    "decode_base64": "worldfoundry.core.utils.misc_utils",
    "deprecated": "worldfoundry.core.utils.functional_utils",
    "divide": "worldfoundry.core.utils.misc_utils",
    "dump_torch": "worldfoundry.core.utils.torch_utils",
    "enable_dict_arg": "worldfoundry.core.utils.functional_utils",
    "enable_kwargs": "worldfoundry.core.utils.functional_utils",
    "enable_list_arg": "worldfoundry.core.utils.functional_utils",
    "enable_varargs": "worldfoundry.core.utils.functional_utils",
    "encode_base64": "worldfoundry.core.utils.misc_utils",
    "env_is_true": "worldfoundry.core.utils.misc_utils",
    "eval_mode": "worldfoundry.core.utils.torch_utils",
    "filter_patterns": "worldfoundry.core.utils.misc_utils",
    "fix_random_seeds": "worldfoundry.core.utils.torch_utils",
    "freeze_params": "worldfoundry.core.utils.torch_utils",
    "has_batchnorms": "worldfoundry.core.utils.torch_utils",
    "func_has_arg": "worldfoundry.core.utils.functional_utils",
    "func_parameters": "worldfoundry.core.utils.functional_utils",
    "get_all_frames": "worldfoundry.core.utils.video_utils",
    "get_batch_size": "worldfoundry.core.utils.array_tensor_utils",
    "get_device": "worldfoundry.core.utils.torch_utils",
    "get_frames_by_indices": "worldfoundry.core.utils.video_utils",
    "get_frames_by_timestamps": "worldfoundry.core.utils.video_utils",
    "get_module_device": "worldfoundry.core.utils.torch_utils",
    "get_seed": "worldfoundry.core.utils.torch_utils",
    "getattr_nested": "worldfoundry.core.utils.misc_utils",
    "getitem_nested": "worldfoundry.core.utils.misc_utils",
    "global_n_times": "worldfoundry.core.utils.misc_utils",
    "global_once": "worldfoundry.core.utils.misc_utils",
    "has_keys": "worldfoundry.core.utils.functional_utils",
    "implements_method": "worldfoundry.core.utils.functional_utils",
    "implements_state_dict": "worldfoundry.core.utils.torch_utils",
    "imread": "worldfoundry.core.utils.image_utils",
    "imsave": "worldfoundry.core.utils.image_utils",
    "imshow": "worldfoundry.core.utils.image_utils",
    "is_array_tensor": "worldfoundry.core.utils.array_tensor_utils",
    "is_mapping": "worldfoundry.core.utils.functional_utils",
    "is_numpy": "worldfoundry.core.utils.array_tensor_utils",
    "is_sequence": "worldfoundry.core.utils.functional_utils",
    "is_signature_compatible": "worldfoundry.core.utils.functional_utils",
    "is_tensor": "worldfoundry.core.utils.array_tensor_utils",
    "load_state_dict": "worldfoundry.core.utils.torch_utils",
    "load_pil_image": "worldfoundry.core.utils.image_utils",
    "load_torch": "worldfoundry.core.utils.torch_utils",
    "make_list": "worldfoundry.core.utils.functional_utils",
    "make_recursive_func": "worldfoundry.core.utils.functional_utils",
    "make_registry_metaclass": "worldfoundry.core.utils.functional_utils",
    "make_tuple": "worldfoundry.core.utils.functional_utils",
    "MaskData": "worldfoundry.core.utils.mask_data",
    "match_patterns": "worldfoundry.core.utils.misc_utils",
    "maybe_transfer_module": "worldfoundry.core.utils.torch_utils",
    "mean_flat": "worldfoundry.core.utils.torch_utils",
    "merge_kwargs": "worldfoundry.core.utils.functional_utils",
    "meta_decorator": "worldfoundry.core.utils.functional_utils",
    "method_decorator": "worldfoundry.core.utils.functional_utils",
    "multi_one_hot": "worldfoundry.core.utils.torch_utils",
    "pack_kwargs": "worldfoundry.core.utils.functional_utils",
    "pack_varargs": "worldfoundry.core.utils.functional_utils",
    "random_derangement": "worldfoundry.core.utils.torch_utils",
    "readable_count_parameters": "worldfoundry.core.utils.torch_utils",
    "remove_batch_dim": "worldfoundry.core.utils.array_tensor_utils",
    "safe_hash": "worldfoundry.core.utils.misc_utils",
    "sanity_check_image_tensor": "worldfoundry.core.utils.image_utils",
    "save_torch": "worldfoundry.core.utils.torch_utils",
    "sequential_split_dataset": "worldfoundry.core.utils.torch_utils",
    "set_deterministic": "worldfoundry.core.utils.torch_utils",
    "set_random_seed": "worldfoundry.core.utils.torch_utils",
    "set_os_envs": "worldfoundry.core.utils.misc_utils",
    "set_requires_grad": "worldfoundry.core.utils.torch_utils",
    "set_seed_everywhere": "worldfoundry.core.utils.torch_utils",
    "setattr_nested": "worldfoundry.core.utils.misc_utils",
    "setitem_nested": "worldfoundry.core.utils.misc_utils",
    "state_dict_class": "worldfoundry.core.utils.functional_utils",
    "tensor_hash": "worldfoundry.core.utils.torch_utils",
    "tie_weights": "worldfoundry.core.utils.torch_utils",
    "to_image": "worldfoundry.core.utils.image_utils",
    "to_state_dict": "worldfoundry.core.utils.torch_utils",
    "torch_compute_stats": "worldfoundry.core.utils.torch_utils",
    "torch_flatten_indices": "worldfoundry.core.utils.torch_utils",
    "torch_load": "worldfoundry.core.utils.torch_utils",
    "torch_multi_index_select": "worldfoundry.core.utils.torch_utils",
    "torch_normalize": "worldfoundry.core.utils.torch_utils",
    "torch_save": "worldfoundry.core.utils.torch_utils",
    "unfreeze_params": "worldfoundry.core.utils.torch_utils",
    "unwrap_ddp_model": "worldfoundry.core.utils.torch_utils",
    "update_soft_params": "worldfoundry.core.utils.torch_utils",
    "weight_init": "worldfoundry.core.utils.torch_utils",
}


def __getattr__(name: str) -> Any:
    module_name = _SUBMODULES.get(name) or _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = module if name in _SUBMODULES else getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})


__all__ = sorted({*_SUBMODULES, *_EXPORT_MODULES})
