model:
  base_learning_rate: 1.0e-5
  target: src.models.fps_predictor.FPSPredictor
  params:
    freeze_encoder: True # Set to False for full finetuning
    hidden_dim: 1024
    warmup_steps: 200
    n_layers: 1
    ckpt_path: ckpts/sota-4-4z.ckpt
    monitor: "val/loss"
    
    # Encoder params (copied from config_4z.yaml)
    embed_dim: 4
    use_quant_conv: True
    
    lossconfig: # Dummy, just to satisfy init
      target: torch.nn.Identity
      
    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 216
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ] 
      temporal_down_factor: 1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0
    
    ppconfig:
      temporal_scale_factor: 4
      z_channels: 4
      out_ch: 4
      ch: 4 # 16*4
      attn_temporal_factor: []
